root: true
parserOptions:
  project: tsconfig.json
  sourceType: module
env:
  node: true
  jest: true
rules:
  'no-console':
    - error
    - allow:
        - error
extends:
  - '@monkee/eslint-config/typescript'
